[versions]
kotlin = "1.9.21"
serialization = "1.6.0"
coroutines = "1.7.3"

[libraries]
kotlin-serialization =  { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref="serialization" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm" , version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }



[bundles]